In [ ]:
import pandas as pd
import numpy as np

In [2]:
pwd

'c:\\Users\\user\\빅데이터_3차프젝'

In [129]:
df_00 = pd.read_csv("./샘플링데이터/00.연체정보_sample/201807_연체정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")
df_01 = pd.read_csv("./샘플링데이터/01.카드 회원정보_sample/201807_회원정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")
df_02 = pd.read_csv("./샘플링데이터/02.카드 신용정보_sample/201807_신용정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")
df_03 = pd.read_csv("./샘플링데이터/03.카드 승인매출정보_sample/201807_승인매출정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")
df_04 = pd.read_csv("./샘플링데이터/04.카드 청구정보_sample/201807_청구정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")
df_05 = pd.read_csv("./샘플링데이터/05.카드 잔액정보_sample/201807_잔액정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")
df_06 = pd.read_csv("./샘플링데이터/06.카드 채널정보_sample/201807_채널정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")
df_07 = pd.read_csv("./샘플링데이터/07.카드 마케팅정보_sample/201807_마케팅정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")
df_08 = pd.read_csv("./샘플링데이터/08.카드 성과정보_sample/201807_성과정보_sample100.csv", usecols=lambda c: c != "Unnamed: 0")


df_09 = pd.read_csv("./샘플링데이터/09.개인 CB정보_sample/201912_개인CB_sample100.csv", usecols=lambda c: c != "Unnamed: 0") # 2019~2022 월말별
df_10 = pd.read_csv("./샘플링데이터/10.기업 CB정보_sample/202108_기업CB_sample100.csv", usecols=lambda c: c != "Unnamed: 0") # 202108~202207 월별
df_11 = pd.read_csv("./샘플링데이터/11.통신카드CB 결합정보_sample/202103_통신카드CB결합_sample100.csv", usecols=lambda c: c != "Unnamed: 0") # 202103~202212 분기별
df_12 = pd.read_csv("./샘플링데이터/12.금융상품정보_sample/공모펀드상품_sample100.csv", usecols=lambda c: c != "Unnamed: 0")

In [130]:
df_09.head(1)

,STDT,ID,GENDER,AGE_BAND,C1Z001373,C1M2B4W03,C1M2B5W03,C1Z001386,C1M210000,C1M210001,...,AL0C00005,AP0910001,AP0910002,AS120G001,SCORE,SCORE_6M,PERF1,PERF2,PERF3,PERF4
0,201912,011EFD71BB7C31440BD738CA4A22526C6964232C85FBF3...,2,4,3631,668,1477,11519,1,0,...,-99999999,9,9,1,953,943,0,0,0,0

In [131]:
missing_cols = df_09.columns[df_09.isnull().any()]

missing_counts = df_09[missing_cols].isnull().sum()

print("개인 CB프레임 내 결측치가 존재하는 열:")
print(missing_cols)
print("\n각 열의 결측치 개수:")
print(missing_counts)

개인 CB프레임 내 결측치가 존재하는 열:
Index(['C1L120001', 'C1L120012', 'C1L120024', 'C1L120171', 'C1L120179',
       'C1L120196', 'C1L120242', 'C1L120251', 'C1L120270', 'C1L120272',
       'U81103010', 'U81205010', 'D10147000', 'D10155000'],
      dtype='object')

각 열의 결측치 개수:
C1L120001    77
C1L120012    77
C1L120024    77
C1L120171    77
C1L120179    57
C1L120196    77
C1L120242    57
C1L120251    57
C1L120270    77
C1L120272    77
U81103010    64
U81205010     2
D10147000    96
D10155000    96
dtype: int64

In [132]:
df_11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Columns: 738 entries, BASE_YM to YOY_R3M_ITRT_COMM_MESSENGER_CS
dtypes: float64(369), int64(363), object(6)
memory usage: 576.7+ KB

In [133]:

# 개인CB 메타데이터 로드
file_path_09 = "./093-117_금융 합성데이터_데이터구성상세 (1).xlsx"
df_09_meta = pd.read_excel(file_path_09, sheet_name="9.개인CB 정보")

# 영문명 → 한글명 매핑 딕셔너리 생성
col_map_09_full = df_09_meta.set_index("필드영문명")["필드한글명"].to_dict()

df_09_renamed = df_09.rename(columns=col_map_09_full)

# 결과 확인
print("매핑된 컬럼 개수:", len(col_map_09_full))
print(list(col_map_09_full.items())[:10])  # 앞부분 10개만 출력
df_09_renamed.head(1)

매핑된 컬럼 개수: 157
[('STDT', '기준년월'), ('ID', '대체 Key'), ('GENDER', '성별'), ('AGE_BAND', '연령'), ('C1Z001373', '3개월내(15일)카드총이용금액(미해지)'), ('C1M2B4W03', '3개월내(15일)신용카드일시불총이용금액(해지포함)'), ('C1M2B5W03', '3개월내(15일)신용카드할부총이용금액합계(해지포함)'), ('C1Z001386', '1년내(15일)카드총이용금액(미해지)'), ('C1M210000', '신용카드건수(미해지)'), ('C1M210001', '신용카드건수(해지포함)(1개월내신규개설)')]

,기준년월,대체 Key,성별,연령,3개월내(15일)카드총이용금액(미해지),3개월내(15일)신용카드일시불총이용금액(해지포함),3개월내(15일)신용카드할부총이용금액합계(해지포함),1년내(15일)카드총이용금액(미해지),신용카드건수(미해지),신용카드건수(해지포함)(1개월내신규개설),...,최근보유차량가격,1년 내 국민연금 성실납부 여부,1년내건강보험료성실납부여부,현거주지평형(구간화),KCB Score,신정일로부터 6개월말 시점 KCB Score,신청일로부터 12개월 내 90일 이상 연체경험 여부,신청일로부터 12개월 내 30일 이상 연체경험 여부,신청일로부터 3개월 내 신규 대출 발생 여부,신청일로부터 6개월내 60일 이상 연체경험 여부
0,201912,011EFD71BB7C31440BD738CA4A22526C6964232C85FBF3...,2,4,3631,668,1477,11519,1,0,...,-99999999,9,9,1,953,943,0,0,0,0

In [134]:
# 통신CB 메타데이터 로드
file_path_11 = "./093-117_금융 합성데이터_데이터구성상세 (1).xlsx"
df_11_meta = pd.read_excel(file_path_11, sheet_name="11.통신카드CB 결합정보")

# 영문명 → 한글명 매핑 딕셔너리 생성
col_map_11_full = df_11_meta.set_index("필드명")["설명"].to_dict()

# 실제 데이터셋 컬럼명 변경
df_11_renamed = df_11.rename(columns=col_map_11_full)

# 결과 확인
print("매핑된 컬럼 개수:", len(col_map_11_full))
print(list(col_map_11_full.items())[:10])  # 앞부분 10개 출력
df_11_renamed.head(1)

매핑된 컬럼 개수: 738
[('BASE_YM', '기준년월'), ('CUST_ID', '고객식별자'), ('SEX', '성별'), ('AGE', '연령대'), ('JB_TP', '직업군'), ('HOME_ADM', '거주지시도'), ('COM_ADM', '근무지시도'), ('HIGHEND_CD1', '하이엔드대상자코드1'), ('HIGHEND_CD2', '하이엔드대상자코드2'), ('HIGHEND_CD3', '하이엔드대상자코드3')]

,기준년월,고객식별자,성별,연령대,직업군,거주지시도,근무지시도,하이엔드대상자코드1,하이엔드대상자코드2,하이엔드대상자코드3,...,전년동기대비_엔터_웹툰/애니_관심도_변화,전년동기대비_엔터_음악_관심도_변화,전년동기대비_정보_뉴스_관심도_변화,전년동기대비_정보_도서/잡지_관심도_변화,전년동기대비_정보_블로그_관심도_변화,전년동기대비_정보_포탈_관심도_변화,전년동기대비_커뮤_SNS_관심도_변화,전년동기대비_커뮤_VoIP_관심도_변화,전년동기대비_커뮤_데이트_관심도_변화,전년동기대비_커뮤_메신저_관심도_변화
0,202103,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,0,-1,0,0,0,-1,0,0

In [137]:
df_09_renamed["신용카드건수(해지포함)(6개월내신규개설)"].value_counts()

신용카드건수(해지포함)(6개월내신규개설)
0    100
Name: count, dtype: int64

In [143]:
def fill_missing_values(df, num_features_zero=[], num_features_median=[], cat_features=[]):
    """
    결측 처리:
    - num_features_zero: 0 대체
    - num_features_median: 중앙값 대체
    - cat_features: "Unknown" + missing flag
    """
    df = df.copy()
    
    # 1) 거래금액 등 의미 있는 0
    for col in num_features_zero:
        if col in df.columns:
            df[col] = df[col].fillna(0)
    
    # 2) 연속형 → 중앙값
    for col in num_features_median:
        if col in df.columns:
            median_val = df[col].median()
            df[col] = df[col].fillna(median_val)
    
    # 3) 범주형 → Unknown + flag
    for col in cat_features:
        if col in df.columns:
            df[col + "_missing"] = df[col].isna().astype(int)
            df[col] = df[col].fillna("Unknown")
    
    return df



# 개인CB 파생변수

def create_features_personal(df_09):
    feats = pd.DataFrame(index=df_09.index)
    
    # 소비 패턴
    if "3개월내(15일)카드총이용금액(미해지)" in df_09 and "1년내(15일)카드총이용금액(미해지)" in df_09:
        feats["소비비율_3Mvs1Y"] = df_09["3개월내(15일)카드총이용금액(미해지)"] / (df_09["1년내(15일)카드총이용금액(미해지)"] + 1)
    
    if "3개월내(15일)신용카드할부총이용금액합계(해지포함)" in df_09 and "3개월내(15일)신용카드일시불총이용금액(해지포함)" in df_09:
        feats["할부비율_3M"] = df_09["3개월내(15일)신용카드할부총이용금액합계(해지포함)"] / (
            df_09["3개월내(15일)신용카드할부총이용금액합계(해지포함)"] + df_09["3개월내(15일)신용카드일시불총이용금액(해지포함)"] + 1
        )
    
    # 카드당 평균 사용액
    if "신용카드건수(미해지)" in df_09:
        feats["카드평균이용액_3M"] = df_09["3개월내(15일)카드총이용금액(미해지)"] / (df_09["신용카드건수(미해지)"] + 1)
    
    # 신규카드 비율
    if "신용카드건수(해지포함)(1개월내신규개설)" in df_09:
        feats["신규카드비율_6M"] = (
            df_09["신용카드건수(해지포함)(1개월내신규개설)"].fillna(0) +
            df_09["신용카드건수(해지포함)(3개월내신규개설)"].fillna(0) +
            df_09["신용카드건수(해지포함)(6개월내신규개설)"].fillna(0)
        ) / (df_09["신용카드건수(미해지)"] + 1)
    
    # 체크카드 비율
    if "체크카드건수(미해지)" in df_09:
        feats["체크카드비율"] = df_09["체크카드건수(미해지)"] / (
            df_09["신용카드건수(미해지)"] + df_09["체크카드건수(미해지)"] + 1
        )
    
    # 한도 대비 이용
    if "카드총한도금액(활성카드)(미해지)" in df_09:
        feats["한도소진율"] = df_09["3개월내(15일)카드총이용금액(미해지)"] / (df_09["카드총한도금액(활성카드)(미해지)"] + 1)
        feats["단기대출비율"] = df_09["신용카드총단기카드대출(CA)한도금액(활성카드)(미해지)"] / (df_09["카드총한도금액(활성카드)(미해지)"] + 1)
    
    # 신용이력
    if "최초신용카드개설일자로부터경과일수(활성카드)(미해지)" in df_09:
        feats["최초개설_경과일"] = df_09["최초신용카드개설일자로부터경과일수(활성카드)(미해지)"]
    if "최초카드개설일로부터경과일수(활성카드)(미해지)" in df_09:
        feats["카드개설_경과일"] = df_09["최초카드개설일로부터경과일수(활성카드)(미해지)"]
    
    return feats



# 통신CB 파생변수
def create_features_telco(df_11):
    feats = pd.DataFrame(index=df_11.index)
    
    # 1) 연체율 (기간 대비 보정)
    if "연체건수(1개월내발생)(해제포함)_전년말기준" in df_11:
        feats["연체율_1M"] = df_11["연체건수(1개월내발생)(해제포함)_전년말기준"] / 1
    if "연체건수(3개월내발생)(해제포함)_전년말기준" in df_11:
        feats["연체율_3M"] = df_11["연체건수(3개월내발생)(해제포함)_전년말기준"] / 3
    if "연체건수(6개월내발생)(해제포함)_전년말기준" in df_11:
        feats["연체율_6M"] = df_11["연체건수(6개월내발생)(해제포함)_전년말기준"] / 6
    if "연체건수(1년내발생)(해제포함)_전년말기준" in df_11:
        feats["연체율_1Y"] = df_11["연체건수(1년내발생)(해제포함)_전년말기준"] / 12
    
    # 2) 연체 심각도
    if "최장연체일수_미해제_전년말기준" in df_11:
        feats["최장연체일수"] = df_11["최장연체일수_미해제_전년말기준"]
    if "총연체금액(미해제)_전년말기준)" in df_11:
        feats["총연체금액"] = df_11["총연체금액(미해제)_전년말기준)"]
    
    # 3) 연체대환 관련
    if "연체대환대출건수(미해지)_전년말기준" in df_11:
        feats["연체대환건수"] = df_11["연체대환대출건수(미해지)_전년말기준"]
    
    # 4) 현재 미해제 연체
    if "연체건수(미해제)(대지급포함)_전년말기준" in df_11:
        feats["미해제연체건수"] = df_11["연체건수(미해제)(대지급포함)_전년말기준"]
    
    return feats

In [156]:
df_11_renamed['연체건수(1개월내발생)(해제포함)_전년말기준'].value_counts()

연체건수(1개월내발생)(해제포함)_전년말기준
0.0    100
Name: count, dtype: int64

In [157]:
df_11_renamed['연체건수(3개월내발생)(해제포함)_전년말기준'].value_counts()

연체건수(3개월내발생)(해제포함)_전년말기준
0.0    99
1.0     1
Name: count, dtype: int64

In [159]:
df_11_renamed['연체대환대출건수(미해지)_전년말기준'].value_counts()

연체대환대출건수(미해지)_전년말기준
0.0    100
Name: count, dtype: int64

In [158]:
df_11_renamed['연체건수(6개월내발생)(해제포함)_전년말기준'].value_counts()

연체건수(6개월내발생)(해제포함)_전년말기준
0.0    98
1.0     2
Name: count, dtype: int64

In [144]:
df_11_renamed['애완동물관심등급'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: 애완동물관심등급
Non-Null Count  Dtype
--------------  -----
100 non-null    object
dtypes: object(1)
memory usage: 928.0+ bytes

In [145]:
missing_cols = df_09_renamed.columns[df_09_renamed.isnull().any()]

missing_counts = df_09_renamed[missing_cols].isnull().sum()


print("-------------------------------------------------------------------------")
print("개인 CB프레임 내 결측치가 존재하는 열:")
print(missing_cols)
print(len(missing_cols))
print("-------------------------------------------------------------------------")
print("\n각 열의 결측치 개수:")
print(missing_counts)

-------------------------------------------------------------------------
개인 CB프레임 내 결측치가 존재하는 열:
Index(['카드총한도금액(활성카드)(미해지)', '신용카드총한도금액(활성카드)(미해지)',
       '신용카드총단기카드대출(CA)한도금액(활성카드)(미해지)', '3개월내신용카드최고한도금액합계(활성카드)(미해지)',
       '카드총한도금액(2+)(활성카드)(미해지)', '1년전(월말)카드총한도금액(활성카드)(미해지)',
       '신용카드총한도금액(2+)(활성카드)(미해지)', '신용카드총단기카드대출(CA)한도금액(2+)(활성카드)(미해지)',
       '1년내(월말)카드최고총단기카드대출(CA)한도금액(활성카드)(미해지)', '1년내(월말)카드최고총한도금액(활성카드)(미해지)',
       '자산평가지수(보유주택매매가신뢰수준)', '자산평가지수(자산평가신뢰수준)', '최근연체해제일자(해제)',
       '최초연체기산일자(해제포함)'],
      dtype='object')
14
-------------------------------------------------------------------------

각 열의 결측치 개수:
카드총한도금액(활성카드)(미해지)                       77
신용카드총한도금액(활성카드)(미해지)                     77
신용카드총단기카드대출(CA)한도금액(활성카드)(미해지)           77
3개월내신용카드최고한도금액합계(활성카드)(미해지)              77
카드총한도금액(2+)(활성카드)(미해지)                   57
1년전(월말)카드총한도금액(활성카드)(미해지)                77
신용카드총한도금액(2+)(활성카드)(미해지)                 57
신용카드총단기카드대출(CA)한도금액(2+)(활성카드)(미해지)       57
1년내(월말)카드최고총단기카드대출(CA)한도금액(활성카드)(미해지)    77
1년내(월말)카드최고총한도금액(활성카드)(미해지)              77
자산평가지수(보유주택매매가신뢰수준)                      64
자산평가지수(자산평가신뢰수준)                          2
최근연체해제일자(해제)                             96
최초연체기산일자(해제포함)                           96
dtype: int64

In [147]:
# 결측 처리
df_09_clean = fill_missing_values(df_09_renamed,num_features_zero=[
        "3개월내(15일)카드총이용금액(미해지)",
        "1년내(15일)카드총이용금액(미해지)",
        "3개월내(15일)신용카드할부총이용금액합계(해지포함)",
        "3개월내(15일)신용카드일시불총이용금액(해지포함)"
    ],num_features_median=[
        "카드총한도금액(활성카드)(미해지)",
        "신용카드총단기카드대출(CA)한도금액(활성카드)(미해지)",
        "신용카드총단기카드대출(CA)이용잔액유효한도소진율(활성카드)",
        "최초신용카드개설일자로부터경과일수(활성카드)(미해지)",
        "최초카드개설일로부터경과일수(활성카드)(미해지)"
    ],cat_features=["성별","연령"])

df_11_clean = fill_missing_values(
    df_11_renamed,
    num_features_zero=[
        "최장연체일수_미해제_전년말기준",
        "연체대환대출건수(미해지)_전년말기준",
        "연체건수(1개월내발생)(해제포함)_전년말기준",
        "연체건수(3개월내발생)(해제포함)_전년말기준",
        "연체건수(6개월내발생)(해제포함)_전년말기준",
        "연체건수(1년내발생)(해제포함)_전년말기준",
        "연체건수(미해제)(대지급포함)_전년말기준",
        "총연체금액(미해제)_전년말기준"
    ],
    num_features_median=[],   # 없음
    cat_features=[]           # 없음
)

### 결측 처리한 feature들로 파생 변수 생성
df_09_features = create_features_personal(df_09_clean)
df_11_features = create_features_telco(df_11_clean)

In [148]:
df_09_clean['성별'].value_counts()

성별
1    52
2    48
Name: count, dtype: int64

In [149]:
df_09_features

,소비비율_3Mvs1Y,할부비율_3M,카드평균이용액_3M,신규카드비율_6M,체크카드비율,한도소진율,단기대출비율,최초개설_경과일,카드개설_경과일
0,0.315191,0.688257,1815.500000,0.0,0.333333,0.159261,0.282205,7447,7282
1,0.043531,-0.000000,444.500000,0.0,0.500000,0.038993,0.282205,5660,5694
2,0.264373,0.603470,4109.750000,0.0,0.555556,0.811722,0.254888,1463,4161
3,0.255081,0.358883,5832.500000,0.0,0.333333,2.442420,0.423367,7352,7650
4,0.567363,0.168279,2865.750000,0.0,0.200000,0.502785,0.282205,8336,7639
...,...,...,...,...,...,...,...,...,...
95,-0.086640,-2.401316,385.000000,0.0,0.250000,0.050660,0.282205,7210,7322
96,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.282205,0,0
97,0.234044,0.466905,3964.166667,0.0,0.250000,1.149867,0.348078,8880,9542
98,0.275417,-0.000000,-341.333333,0.0,0.500000,-0.044914,0.282205,1207,2109
99,0.167557,0.336575,1009.800000,0.0,0.500000,0.297245,0.350759,2553,3761

In [152]:
df_11_features

    연체율_1M  연체율_3M  연체율_6M  연체율_1Y  최장연체일수  연체대환건수  미해제연체건수
0      0.0     0.0     0.0     0.0     0.0     0.0      0.0
1      0.0     0.0     0.0     0.0     0.0     0.0      0.0
2      0.0     0.0     0.0     0.0     0.0     0.0      0.0
3      0.0     0.0     0.0     0.0     0.0     0.0      0.0
4      0.0     0.0     0.0     0.0     0.0     0.0      0.0
..     ...     ...     ...     ...     ...     ...      ...
95     0.0     0.0     0.0     0.0     0.0     0.0      0.0
96     0.0     0.0     0.0     0.0     0.0     0.0      0.0
97     0.0     0.0     0.0     0.0     0.0     0.0      0.0
98     0.0     0.0     0.0     0.0     0.0     0.0      0.0
99     0.0     0.0     0.0     0.0     0.0     0.0      0.0

[100 rows x 7 columns]

In [155]:
df_11_features['최장연체일수'].value_counts()

최장연체일수
0.0    100
Name: count, dtype: int64

In [160]:
df_09_features.columns

Index(['소비비율_3Mvs1Y', '할부비율_3M', '카드평균이용액_3M', '신규카드비율_6M', '체크카드비율', '한도소진율',
       '단기대출비율', '최초개설_경과일', '카드개설_경과일'],
      dtype='object')

In [162]:
df_11_features.columns

Index(['연체율_1M', '연체율_3M', '연체율_6M', '연체율_1Y', '최장연체일수', '연체대환건수', '미해제연체건수'], dtype='object')

In [ ]:
"""
개인CB/통신CB 파생변수를 만든 이유와 역할
---------------------------------------

[개인CB 파생변수]
- 소비비율_3Mvs1Y  : 최근 단기 소비 증가율 → 소비 급증 집단의 리스크 검증
- 할부비율_3M      : 단기 부채 의존도 → 잠재 연체 위험 반영 여부 확인
- 카드평균이용액_3M : 카드당 평균 사용 강도 → 고소득/과소비 집단 구분
- 신규카드비율_6M  : 최근 신용 확장 속도 → 과도한 신용 팽창 집단 위험 점검
- 체크카드비율     : 보수적 소비 성향 집단 → 낮은 위험 반영 여부 확인
- 한도소진율       : 한도 대비 사용 비율 → 과소비/여력 부족 집단 확인
- 단기대출비율     : 단기대출 의존도 → 연체 위험 증가 신호 검증
- 최초개설_경과일   : 신용 히스토리 길이 → 짧은 신용이력 집단의 위험 확인
- 카드개설_경과일   : 전체 카드 보유 경력 → 신용 안정성 검증

[통신CB 파생변수]
- 연체율_1M / 3M / 6M / 1Y : 기간별 연체 발생률 → 단기/장기 납부습관 확인
- 최장연체일수             : 연체 심각도 지표 → 위험 집단의 지속성 검증
- 연체대환건수             : 대환대출로 막은 연체 → 숨겨진 리스크 검증
- 미해제연체건수           : 현재 진행 중인 연체 → 실질적 위험 수준 확인

[종합적 역할]
- 내부 모델(M1)의 출력값: 연체 위험도, 신용등급 변화
- 외부 CB 지표의 역할   : 집단 단위 소비·신용행태·연체습관을 통해
                          내부 모델이 특정 집단을 과대/과소평가했는지 검증
- 즉, 개인CB는 '소비·신용여력·이력' 관점, 
     통신CB는 '납부성실·연체패턴' 관점에서
     모델 출력 결과를 외부적으로 보정하는 참고 지표로 사용된다.
"""